/*
 * generated by Xtext 2.10.0
 */
package biz.stillhart.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GeneratorStandaloneSetup extends GeneratorStandaloneSetupGenerated {

	def static void doSetup() {
		new GeneratorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
