/*
 * generated by Xtext 2.10.0
 */
package biz.stillhart.xtext.ide.contentassist.antlr;

import biz.stillhart.xtext.ide.contentassist.antlr.internal.InternalGeneratorParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class GeneratorTokenSource extends AbstractIndentationTokenSource {

	public GeneratorTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalGeneratorParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalGeneratorParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalGeneratorParser.RULE_END;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
